
module: KituraKit
author: IBM
github_url: https://github.com/Kitura-Next/KituraKit

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraKit.xcodeproj, -target, KituraKit, LIBRARY_SEARCH_PATHS=.build/debug]
